### PR TITLE
python3 version

### PR DESCRIPTION
**Pull request by bgruening**
* [ ] Flake8 passes (`flake8 . --exclude=.venv,.build,planemo_test_env,build --ignore=E501,F403,E402,F999,F405,E712`)
* [ ] Local tests pass (`py.test hicexplorer --doctest-modules`)

### CODE REVIEW

**Comment by bgruening** [comment]
@joachimwolff this is the python3 version of the function. Under py3k an input of `chr21` is not taken into account and reports an argparse error later on. This PR needs to checked if it is python2 compliant or if there are some six magic that can be used.

**Comment by joachimwolff** [comment]
This is related to #242 I guess?

**Comment by bgruening** [comment]
Yes it is. Bug report from yesterday in your Galaxy inbox ;) I solved this locally.

**Comment by fidelram** [comment]
I hope this is the last python3 bug

**Pull request merged**
