### PR TITLE
log file name and header changed to make more specific multiqc recogn…

### PR DESCRIPTION
**Pull request by vivekbhr**
* [x] Flake8 passes (`flake8 . --exclude=.venv,.build,planemo_test_env,build --ignore=E501,F403,E402,F999,F405,E712`)
* [x] Local tests pass (`py.test hicexplorer --doctest-modules`)

Minor change, but this would fix the issue of MultiQC module breaking under recursive mode for HiCEx log files. A parallel PR to multiQC would be opened once it's done (I am working on more useful coloring scheme there).

### CODE REVIEW

**Comment by joachimwolff** [comment]
@vivekbhr You deleted two test files, but you forgot to replace them by the new ones.

**Comment by joachimwolff** [comment]
@vivekbhr I would like to include this PR in the next release. Because there is a high demand for new tools and bug fixed implementations, I want to release it within the next week.

**Comment by vivekbhr** [comment]
I can fix the PR if the next release is not this weekend. would that work?

**Comment by joachimwolff** [comment]
Sure.

**Comment by LeilyR** [comment]
This can be fixed on multiqc. we need to call multiqc on a different line which is not share between several files in the qc path.

**Pull request closed without merging**
