### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by gtrichard**
I began to improve the documentation at the "python level" when the user tries to get a quick help on a specific tool by using "name_of_the_tool --help". This pull is a Work In Progress.

Example usage and example output in .rst files will be added soon. Also a QC tutorial will be added in the general Example Usage of HiCExplorer.

Help for tools still in development like hicAggregateContacts, which is currently being tested, will also be added and a tutorial of this tool will be added in Example Usage as a downstream analysis step.

Tools grouping just like in Deeptools is also planned (Processing tools, QC tools, Plotting tools). 

* [ ] Flake8 passes (`flake8 . --exclude=.venv,.build,planemo_test_env,build --ignore=E501,F403,E402,F999,F405,E712`)
* [ ] Local tests pass (`py.test hicexplorer --doctest-modules`)

### CODE REVIEW

**Comment by bgruening** [comment]
@gtrichard it is possible to generate the commandline args automatically out of argparse, using sphinx-argparse. This way we do not need to keep them manually updated.

We used this for example here: https://github.com/galaxyproject/ephemeris

**Comment by joachimwolff** [comment]
Please have consider the file sizes you upload. ~4 MB for docs/images/hicPlotMatrix.png and ~16 MB for docs/images/hicPlotMatrix_perChr.png is too much. Both should have less than 500 kb.

**Comment by gtrichard** [comment]
@joachimwolff This will be changed, thank you for pointing this error.

I think that a page describing the goal of each kind of "matrix score" is mandatory. For example, what is the advantage, the disadvantage, and what is the purpose of z-score, obs/exp and pearson matrices that be can calculated with hicTransform and/or hicFindEnrichedContacts?

These tools also need better help, but I haven't tested them and I lack insight about what are the differences and the purpose of each of these scores...

This page should be a part of "Example usage" I think.

**Comment by joachimwolff** [comment]
Thanks for your contributions so far. Two more thinks, one minor, one major:
1. Please have a look at the linting of the markdown files. I get a few warning messages by running a simple `make html` in the docs folder. To use this command you need `sphinx`
2. For some reasons the build of our documentation on readthedocs fails. Please register an account and I will add you to the project. It would be very helpful for us to figure out what is going wrong.

**Comment by gtrichard** [comment]
@joachimwolff 

1. Yes I saw this today when I built my own readthedoc with sphinx. I have a reference for each of them so I will push a commit to correct all these errors.

2. I also saw that... Here is my readthedoc account: https://readthedocs.org/profiles/grichard/ . Although it is "failing" according to github I can build the documentation perfectly fine with sphinx... I receive these errors though, so maybe the build of the documentation is "failing" because of these:

```
checking consistency... /Users/richard/Documents/github/HiCExplorer/docs/content/tools/findRestSite.rst: WARNING: document isn't included in any toctree
/Users/richard/Documents/github/HiCExplorer/docs/content/tools/hicAggregateContacts.rst: WARNING: document isn't included in any toctree
/Users/richard/Documents/github/HiCExplorer/docs/content/tools/hicBuildMatrix.rst: WARNING: document isn't included in any toctree
/Users/richard/Documents/github/HiCExplorer/docs/content/tools/hicCompareMatrices.rst: WARNING: document isn't included in any toctree
/Users/richard/Documents/github/HiCExplorer/docs/content/tools/hicCorrectMatrix.rst: WARNING: document isn't included in any toctree
/Users/richard/Documents/github/HiCExplorer/docs/content/tools/hicCorrelate.rst: WARNING: document isn't included in any toctree
/Users/richard/Documents/github/HiCExplorer/docs/content/tools/hicExport.rst: WARNING: document isn't included in any toctree
/Users/richard/Documents/github/HiCExplorer/docs/content/tools/hicFindEnrichedContacts.rst: WARNING: document isn't included in any toctree
/Users/richard/Documents/github/HiCExplorer/docs/content/tools/hicFindTADs.rst: WARNING: document isn't included in any toctree
/Users/richard/Documents/github/HiCExplorer/docs/content/tools/hicInfo.rst: WARNING: document isn't included in any toctree
/Users/richard/Documents/github/HiCExplorer/docs/content/tools/hicMergeMatrixBins.rst: WARNING: document isn't included in any toctree
/Users/richard/Documents/github/HiCExplorer/docs/content/tools/hicMergeTADbins.rst: WARNING: document isn't included in any toctree
/Users/richard/Documents/github/HiCExplorer/docs/content/tools/hicPCA.rst: WARNING: document isn't included in any toctree
/Users/richard/Documents/github/HiCExplorer/docs/content/tools/hicPlotDistVsCounts.rst: WARNING: document isn't included in any toctree
/Users/richard/Documents/github/HiCExplorer/docs/content/tools/hicPlotMatrix.rst: WARNING: document isn't included in any toctree
/Users/richard/Documents/github/HiCExplorer/docs/content/tools/hicPlotTADs.rst: WARNING: document isn't included in any toctree
/Users/richard/Documents/github/HiCExplorer/docs/content/tools/hicPlotViewpoint.rst: WARNING: document isn't included in any toctree
/Users/richard/Documents/github/HiCExplorer/docs/content/tools/hicQC.rst: WARNING: document isn't included in any toctree
/Users/richard/Documents/github/HiCExplorer/docs/content/tools/hicSumMatrices.rst: WARNING: document isn't included in any toctree
/Users/richard/Documents/github/HiCExplorer/docs/content/tools/hicTransform.rst: WARNING: document isn't included in any toctree
done
preparing documents... done
writing output... [100%] index
/Users/richard/Documents/github/HiCExplorer/docs/content/News.rst:: WARNING: Could not obtain image size. :scale: option is ignored.
/Users/richard/Documents/github/HiCExplorer/docs/content/example_usage.rst:: WARNING: Could not obtain image size. :scale: option is ignored.
/Users/richard/Documents/github/HiCExplorer/docs/index.rst:40: WARNING: undefined label: hiclog2ratio (if the link has no caption the label must precede a section header)
generating indices... genindex
writing additional pages... search
copying images... [100%] content/tools/../../images/hicMergeMatrixBins_Xchr.png
copying static files... WARNING: html_static_path entry u'/Users/richard/Documents/github/HiCExplorer/docs/_static' does not exist
```

**Comment by joachimwolff** [comment]
1. Great!
2. I know it builds on my local machine too. These errors were always there and it was working somehow. I just thought that you see maybe something I don't. Would be cool if we can get this somehow running again. Currently I try to use old versions of sphinx in the hope it works... :) Let's see.

**Comment by gtrichard** [comment]
I'll try to see if I can do something about this :)

I need feedback about my last 2 commits, if these changes are well made according to you (I am a python beginner), I can do it for every .py script, it will allow us to get a cleaner help, both in command-line and in the readthedocs.

I am referring to ``.add_argument_group('Required arguments')`` and ``.add_argument_group('Optional arguments')``.

**Comment by joachimwolff** [comment]
@gtrichard I will take care of this tomorrow.
@fidelram @bgruening FYI: I played version bingo with the dependencies for readthedocs and using the combination of the outdated software: `sphinx==1.5.0`, `docutils==0.12` was finally working, the documentation is building again.

**Comment by fidelram** [comment]
@gtrichard I agree with the changes that you suggest. I just checked hicCorrectMatrix and it is working properly, I see the two groups one for the Required Arguments and other for the optional.

Can you also make the following change of the description of the tool. It should say:

```
Iterative correction for a Hi-C matrix (see Imakaev et al. 2012
Nature Methods for details). For the method to work correctly, bins with
zero reads assigned to them should be removed as they can not be corrected.
Also, bins with low number of reads should be removed, 
otherwise, during the correction step, the counts associated with 
those bins will be amplified (usually, zero and low coverage bins 
tend contain repetitive regions).  Bins with extremely high number
of reads can also be removed from the correction as they may represent 
copy number variations.

To aid in the identification of bins with low and high read coverage, the
histogram of the number of reads can be plotted together with the
Median Absolute Deviation (MAD).
```

Actually, in order for all of us to contribute to the documentation I will open a branch called documentation and I will merge this branch to it.

**Pull request merged**
