### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by fidelram**
* [ ] Flake8 passes (`flake8 . --exclude=.venv,.build,planemo_test_env,build --ignore=E501,F403,E402,F999,F405,E712`)
* [ ] Local tests pass (`py.test hicexplorer --doctest-modules`)

### CODE REVIEW

**Comment by joachimwolff** [comment]
I cherry-picked the one commit from 2.0.1-bugfix branch fixing the py3 issue of hicAggregatePlot. I hope there were no changes on this which are in any conflict of this.

**Comment by fidelram** [comment]
@joachimwolff I don't have any errors locally when testing `hicAggregateContacts` can you check if you also get the error? Probably is some version issue.

**Comment by joachimwolff** [comment]
It is passing with Python 2 and Python 3. The usual candidate for this kind of issue is matplotlib but its version is fixed to 2.1.1.

**Comment by joachimwolff** [comment]
Is the work on this branch done? I would like to release a new version this week.

**Comment by joachimwolff** [comment]
The files `docs/images/hicCompareMatrices_m1bp_over_gst_log2_m50_matrix_plot.png`
and `docs/images/hicMergeMatrixBins_Xregion.png` need to be recomputed, their diagonal is wrong.

**Comment by fidelram** [comment]
@joachimwolff I have the updated image for `docs/images/hicCompareMatrices_m1bp_over_gst_log2_m50_matrix_plot.png`.

**Comment by gtrichard** [comment]
The work is done I think, it would need better documentation for some tools and also a step by step and integrative tutorial for QC of Hi-C data. But this can be done in a new branch, so maybe this branch can be merged with 2.0.1 bug fix or master after resolving the building and the conflicts.

**Comment by joachimwolff** [comment]
I resolved the conflicts locally and merged them. Closing this PR.

**Pull request closed without merging**
