### PR TITLE
Initialize fail_flag and fail_message even if single_core

### PR DESCRIPTION
**Pull request by alecw**
If running on a single chromosome, these variables were not being set, resulting in the
error:

Traceback (most recent call last):
  File "/opt/anaconda2/envs/HiCExplorer/bin/hicDetectLoops", line 7, in <module>
    main()
  File "/opt/anaconda2/envs/HiCExplorer/lib/python3.6/site-packages/hicexplorer/hicDetectLoops.py", line 1072, in main
    if fail_flag:
UnboundLocalError: local variable 'fail_flag' referenced before assignment

* [ ] Flake8 passes (`flake8 . --exclude=.venv,.build,planemo_test_env,build --ignore=E501,F403,E402,F999,F405,E712`)
* [ ] Local tests pass (`py.test hicexplorer --doctest-modules`)

### CODE REVIEW

**Comment by LeilyR** [comment]
Hi @alecw , thanks for the PR. Could you please send it to our develop?

**Comment by alecw** [comment]
Hi @LeilyR,

Looks like this has been taken care of.  Please let me know if there is anything you need me to do.

Regards, Alec

**Comment by LeilyR** [comment]
please fix README.rst to match our dev

**Comment by alecw** [comment]
Hi @LeilyR ,

I rebased my change onto develop branch.  I'm guessing that is what you wanted me to do.

It would be helpful if you use specific git terminology in the things you are asking me to do.  E.g. instead of saying "Could you please send it to our develop," which leaves me wondering "what is develop," you could say "could you rebase your changes on the develop branch, and submit your pull request relative to the develop branch." 

Regards, Alec

**Comment by joachimwolff** [comment]
Hi,

most of our users are biomedicals and not familiar with git or its terminology. Given your very limited actions on github in the last year, we assumed this for you too. However, knowing git but not knowing that 'develop' or simply 'dev' means our development branch is also bit weird because this is kind of common sense.

Best,

Joachim

**Comment by LeilyR** [comment]
Thanks for the contribution!

**Pull request merged**
