### PR TITLE
Fix an error occurring when hicExport writes to gzipped text files in Python 3

### PR DESCRIPTION
**Pull request by ajank**
`gzip.open` by default opens file in binary mode (unlike the regular `open`). In Python 3, an attempt to write a string to a binary-open file fails with `TypeError: memoryview: a bytes-like object is required, not 'str'`. To prevent this error, the file should be open in text mode ("wt" instead of "w") in the first place.

See https://stackoverflow.com/questions/41050881/write-to-gzipped-fasta-file-in-python-3-5

### CODE REVIEW

**Comment by fidelram** [comment]
Do you know if these changes also work with python2?

**Comment by ajank** [comment]
Good question! The changes also work with Python 2.7.14.

**Comment by joachimwolff** [comment]
@ajank Thanks a lot for your contribution. 

I would like to collect all fixes for the 2.0 version in the branch `2.0.1-bugfix`. Can you change the base branch for the PR to `2.0.1-bugfix`? It is described [here](https://github.com/blog/2224-change-the-base-branch-of-a-pull-request) how to do that. Thanks!

**Comment by dpryan79** [comment]
@joachimwolff I've redirected the PR.

**Comment by joachimwolff** [comment]
@dpryan79 Thanks! I recognized just a bit later that I can do this on my own too :)

**Comment by rachadele** [comment]
hi, I'm getting this error using python 3.6 trying to run hicFindTADs on a cooler. here's the message I'm getting:
Traceback (most recent call last):
  File "/usr/local/bin/hicFindTADs", line 7, in <module>
    main()
  File "/usr/local/lib/python3.6/dist-packages/hicexplorer/hicFindTADs.py", line 1378, in main
    ft.hic_ma.save(args.outPrefix + "_zscore_matrix.h5")
  File "/usr/local/lib/python3.6/dist-packages/hicmatrix/HiCMatrix.py", line 111, in save
    self.matrixFileHandler.save(pMatrixName, pSymmetric=pSymmetric, pApplyCorrection=pApplyCorrection)
  File "/usr/local/lib/python3.6/dist-packages/hicmatrix/lib/matrixFileHandler.py", line 51, in save
    self.matrixFile.save(pName, pSymmetric, pApplyCorrection)
  File "/usr/local/lib/python3.6/dist-packages/hicmatrix/lib/cool.py", line 388, in save
    if self.hic_metadata is not None and 'matrix-generated-by' in self.hic_metadata:
TypeError: a bytes-like object is required, not 'str'

looks like it's having trouble saving the TAD score matrix...not sure if this is a bug or an issue with my data?

**Pull request merged**
