### PR TITLE
Aggregate develop patch

### PR DESCRIPTION
**Pull request by lldelisle**
I think I solve some issues...

### CODE REVIEW

**Comment by LeilyR** [comment]
Have you tested this branch? I have tried and it keeps failing using several matrices and bed files. Also, I am not sure if this is the most efficient way looking for all the intervals of a bed file regardless of their chromosomes. Inspired by this branch, I ended up making my own branch to compute the aggregate contacts of all region in a bed file. I suppose that was the purpose this code. I would like to ask you to wait for my changes to be there before we merge anything. Is that alright by you? I would appreciate your comment on my changes when they are out.

**Comment by lldelisle** [comment]
Hi,
This branch worked for me with cool matrices... No problem to wait for your changes, I just needed it 'quick and dirty' so I wrote a PR but no problem to review yours.

**Comment by LeilyR** [comment]
I think it most likely has something to do with the more recent changes of hicAggregate. I have merged develop to it and it is not working.

**Comment by LeilyR** [comment]
these might have already been addressed in #617 and to be merged to develop. Please have a look and update your PR if needed.

**Pull request closed without merging**
