### PR TITLE
Average regions bugfix

### PR DESCRIPTION
**Pull request by LeilyR**
* [ ] Flake8 passes (`flake8 . --exclude=.venv,.build,planemo_test_env,build --ignore=E501,F403,E402,F999,F405,E712`)
* [ ] Local tests pass (`py.test hicexplorer --doctest-modules`)

### CODE REVIEW

**Comment by lldelisle** [comment]
I think you should consider cases (rare but existing especially with small contigs) where both start_out and end_out. In this case, except if you kept the viewpoint bin, you cannot use this region.

**Comment by LeilyR** [comment]
I am still not so sure if these changes are making sense or just introducing more bias. I am investigating them now.

**Comment by gtrichard** [comment]
Leily is implementing an option to include the edges or not. 

Edges will be included by replacing the non-existing bins by NAs that should be omitted while computing the average. We don't want to replace them by 0s at will change the average computation too much.

**Comment by LeilyR** [comment]
this is still not so good if `--rangeInBins`, because it may returns bins of an other chr instead of the current chr when it reaches the border! I will work on it

**Comment by LeilyR** [comment]
> this is still not so good if `--rangeInBins`, because it may returns bins of an other chr instead of the current chr when it reaches the border! I will work on it

This issue is already solved in the last commit.

**Pull request merged**
